config/routes.rb
CiljiApp::Application.routes.draw do
	root 'goals#index'

	resources :goals, except: :show

  

end

app/models/goal.rb
class Goal < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	def index
		@goals = Goal.all
	end

	def new
		@goal = Goal.new
	end

	def create
		@goal = Goal.new(goals_params)

		if @goal.save
			redirect_to root_path
		else
			render :new
		end

	end

	def edit
		@goal = Goal.find(params[:id])
	end

	def update
		@goal = Goal.find(params[:id])

		if @goal.update(goals_params)
			redirect_to root_path
		else
			render 'edit'
		end

	end

	def destroy
		@goal = Goal.find(params[:id])
		@goal.destroy
		redirect_to root_path
	end
	private
	def goals_params 
		params.require(:goal).permit(:goals_name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/edit.html.erb
<h1>Uredi cilj</h1>
<%= form_for @goal do |f| %>
	<%= f.text_field :goals_name %><br>
	<%= f.submit 'shrani' %>
<% end %>

app/views/goals/index.html.erb
<h1>Dnevni cilji</h1>
<% if @goals.empty? %>
	<p>Nimaš nobenih neizpolnjenih ciljev. Ti si car!</p>
<% else %>
	<ul>
	<% @goals.each do |goal| %>
		<li><%= link_to goal.goals_name, edit_goal_path(goal) %>
	<%= link_to 'izbriši cilj', goal_path(goal), method: :delete, data: { confirm: "Ali si prepričan, da želiš izbrisati cilj" } %>
	</li>
	<% end %>
	</ul>
<% end %>
<%= link_to 'Nov cilj', new_goal_path %>

app/views/goals/new.html.erb
<h1>Nov Cilj</h1>
<%= form_for @goal do |f| %>
	<%= f.text_field :goals_name %><br>
	<%= f.submit 'shrani' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CiljiApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>